- .gitignore
- pom.xml
- src/main/java/com/shopify/minishopify/HomeController.java
- src/main/java/com/shopify/minishopify/MiniShopifyApplication.java
- src/main/resources/application.properties
- src/test/java/com/shopify/minishopify/HomeControllerTest.java
> IntelliJ Project Starter

- .travis.yml
Adding .travis.yml to setup the CI. Closes #4
> ci: configure ci for the project

- .run/MiniShopifyApplication.run.xml
- README.md
This change shall add a run configuration for mini shopify and instructions for setting up the project after being pulled from this repo.
> chore: Added Run Configuration for Mini-Shopify

- src/main/resources/db/migration/V002__Shopify_tables.sql
This pr adds all the necessary tables.
> feat: add tag and category table

- .run/All Unit Tests.run.xml
- pom.xml
- src/main/java/com/shopify/minishopify/model/Category.java
- src/main/java/com/shopify/minishopify/model/Product.java
- src/main/java/com/shopify/minishopify/model/Shop.java
- src/main/java/com/shopify/minishopify/model/Tag.java
- src/main/java/com/shopify/minishopify/model/User.java
- src/main/java/com/shopify/minishopify/repository/CategoryRepository.java
- src/main/java/com/shopify/minishopify/repository/ProductRepository.java
- src/main/java/com/shopify/minishopify/repository/ShopRepository.java
- src/main/java/com/shopify/minishopify/repository/TagRepository.java
- src/main/java/com/shopify/minishopify/repository/UserRepository.java
- src/main/resources/application.properties
- src/main/resources/db/migration/V002__Shopify_tables.sql
- src/test/java/com/shopify/minishopify/model/CategoryTest.java
- src/test/java/com/shopify/minishopify/model/ProductTest.java
- src/test/java/com/shopify/minishopify/model/ShopTest.java
- src/test/java/com/shopify/minishopify/model/TagTest.java
- src/test/java/com/shopify/minishopify/model/UserTest.java
This change adds the model objects to the project, as well as their DB repositories, and tests for persistence.
Closes #31
> feat: Add Model Objects to Project 

- shopify-client/src/App.vue
- shopify-client/src/router/index.js
- shopify-client/src/views/ShopList.vue
- src/main/java/com/shopify/minishopify/controllers/ShopController.java
- src/main/java/com/shopify/minishopify/repository/ShopRepository.java
- src/test/java/com/shopify/minishopify/controllers/ShopControllerTest.java
This pr adds the shop filter in shop controller.
Also adds the store list view.
Closes #26
> feat: add List of Stores view

- shopify-client/src/router/index.js
- shopify-client/src/views/ShopDetails.vue
> feat: Shop detail view

- shopify-client/src/components/ProductForm.vue
- shopify-client/src/components/ShopForm.vue
- shopify-client/src/router/index.js
- shopify-client/src/views/ProductCreate.vue
- shopify-client/src/views/ProductDetails.vue
- shopify-client/src/views/ProductUpdate.vue
- shopify-client/src/views/ShopDetails.vue
- shopify-client/src/views/ShopUpdate.vue
This pr adds a create product button on the shop details page. A link back to the shop that the product belongs to is also added.  An issue with update shop is also fixed.
> feat: integrate product with shop

- shopify-client/src/views/ProductCreate.vue
- shopify-client/src/views/ShopUpdate.vue
Adds back button the Shop update form and Add Product form to return to the Shop details view
> feat: Add back buttons to Shop update and Add product forms

- shopify-client/src/router/index.js
This PR adds the redirection from / to /app. Please ignore the `,` and `'` changes. This is due to my code formatter.
Closes #60
> feat: redirect / to /app

- src/main/java/com/shopify/minishopify/controllers/CategoryController.java
- src/main/java/com/shopify/minishopify/controllers/TagController.java
- src/main/java/com/shopify/minishopify/model/Product.java
- src/main/java/com/shopify/minishopify/repository/CategoryRepository.java
- src/main/java/com/shopify/minishopify/repository/ShopRepository.java
- src/main/java/com/shopify/minishopify/repository/TagRepository.java
- src/test/java/com/shopify/minishopify/controllers/CategoryControllerTests.java
- src/test/java/com/shopify/minishopify/controllers/ProductControllerTest.java
- src/test/java/com/shopify/minishopify/controllers/ShopControllerTest.java
- src/test/java/com/shopify/minishopify/controllers/TagControllerTest.java
- src/test/java/com/shopify/minishopify/model/TagTest.java
- src/test/java/com/shopify/minishopify/model/UserTest.java
Adds Controllers to the backend that allow for categories and tags to Shops.
Part of Issue #55
> Feat: Add Categories and Tags to Shop Controller

- shopify-client/src/views/ShopList.vue
> fix: shop list view img size

- README.md
> doc: Update ReadMe

- shopify-client/src/components/Header.vue
- src/main/java/com/shopify/minishopify/repository/ShopRepository.java
> Feat: Search bar

- shopify-client/src/components/Header.vue
- shopify-client/src/router/index.js
- shopify-client/src/store/index.js
- shopify-client/src/views/Cart.vue
- shopify-client/src/views/Checkout.vue
- shopify-client/src/views/CheckoutSuccess.vue
- shopify-client/src/views/ShopCreate.vue
- src/main/java/com/shopify/minishopify/controllers/CheckoutController.java
- src/main/java/com/shopify/minishopify/viewmodel/Checkout.java
- src/main/java/com/shopify/minishopify/viewmodel/CheckoutList.java
- src/test/java/com/shopify/minishopify/controllers/CheckoutControllerTest.java
This PR adds the ability to checkout. 
Closes #54
> feat: add checkout

- shopify-client/src/views/ShopDetails.vue
> fix: Shop details product uniform size

- shopify-client/src/components/ShopForm.vue
- shopify-client/src/views/Home.vue
- shopify-client/src/views/ShopCreate.vue
- shopify-client/src/views/ShopDetails.vue
- src/main/java/com/shopify/minishopify/controllers/CategoryController.java
- src/main/java/com/shopify/minishopify/controllers/ShopController.java
- src/main/java/com/shopify/minishopify/controllers/TagController.java
- src/main/java/com/shopify/minishopify/model/Shop.java
This adds the option to add categories and tags when creating/updating a store. It also allows you to remove tags that are already associated with the store.
Closes #55
> feat: Add Tag and Category to Shop form

- pom.xml
- src/main/java/com/shopify/minishopify/MiniShopifyApplication.java
- src/main/java/com/shopify/minishopify/config/SecurityConfig.java
- src/main/java/com/shopify/minishopify/security/xss/XSSFilter.java
- src/main/java/com/shopify/minishopify/security/xss/XSSRemover.java
- src/main/java/com/shopify/minishopify/security/xss/XSSRequestWrapper.java
- src/main/resources/ESAPI.properties
- src/main/resources/esapi-java-logging.properties
- src/main/resources/validation.properties
This PR adds XSS protection by striping dangerous content from
- Request header
- Request parameter
- Request body
> feat: add xss protection

- src/main/java/com/shopify/minishopify/controllers/CheckoutController.java
- src/test/java/com/shopify/minishopify/controllers/CheckoutControllerTest.java
This PR updates inventory when an order has been placed successfully.
Closes #93
> fix: inventory not updating on checkout

- shopify-client/src/components/Header.vue
> Update Cart Header

- shopify-client/package.json
- shopify-client/src/App.vue
- shopify-client/src/components/Header.vue
- shopify-client/src/store/index.js
- shopify-client/yarn.lock
Saves shopping cart in a cookie for anonymous users.
Closes #70
> feat: Shopping cart persistence with cookies

- shopify-client/src/components/ProductForm.vue
- shopify-client/src/components/ShopForm.vue
- shopify-client/src/views/ProductDetails.vue
- shopify-client/src/views/ShopDetails.vue
- shopify-client/src/views/ShopList.vue
- src/main/java/com/shopify/minishopify/controllers/ProductController.java
- src/main/java/com/shopify/minishopify/controllers/ShopController.java
- src/main/java/com/shopify/minishopify/util/ImageValidator.java
This PR adds validation for shop and product image. Currently, the validation is done by checking if the image is Base64 encoded.
Closes #38
> feat: add image validation

- src/main/java/com/shopify/minishopify/controllers/ShopController.java
- src/main/java/com/shopify/minishopify/repository/ShopRepository.java
- src/test/java/com/shopify/minishopify/controllers/ShopControllerTest.java
close #80 
Query now considers tags and categories
> Shop list query update

- shopify-client/src/components/ProductForm.vue
- shopify-client/src/components/ShopForm.vue
- shopify-client/src/views/ProductDetails.vue
- shopify-client/src/views/ShopDetails.vue
- shopify-client/src/views/ShopList.vue
- src/main/java/com/shopify/minishopify/util/ImageValidator.java
- src/test/java/com/shopify/minishopify/controllers/ProductControllerTest.java
- src/test/java/com/shopify/minishopify/controllers/ShopControllerTest.java
This PR fixes the image validation so that image types other than png can be used.
> fix: allow other type of images

- shopify-client/src/views/ShopDetails.vue
Add a search bar in the product catalog for shops to filter for products by input.
Closes #115
> feat: Product catalog search bar

- src/main/java/com/shopify/minishopify/controllers/ShopController.java
This PR fixes the update action in ShopController so that it updates the image also.
Closes #118
> fix: update shop image

- shopify-client/src/views/About.vue
- src/main/java/com/shopify/minishopify/controllers/UtilController.java
- src/test/java/com/shopify/minishopify/controllers/UtilControllerTest.java
This change updates our about page to better inform users about our project.
It adds an endpoint that is used to fetch statistics about our system.
Closes #94
> feat: updates About page

- shopify-client/src/views/ShopDetails.vue
- src/main/java/com/shopify/minishopify/controllers/ShopController.java
- src/main/java/com/shopify/minishopify/model/User.java
- src/test/java/com/shopify/minishopify/controllers/ShopControllerTest.java
Add a button on Shop details page to delete the shop.
Closes #121
> feat: Add option to delete shop

- README.md
Quick PR to update the Travis link since we switched the owner of the repo.
> docs: update link to Travis

- src/main/java/com/shopify/minishopify/controllers/ShopController.java
- src/main/java/com/shopify/minishopify/repository/ShopRepository.java
> fix: remove case sensitivity
